name: Belper Town Wind Band
description: Playing together and enjoying music since 1999
baseurl: '/'
keywords: 

url: "https://berthelemy.github.io"

paginate: 10

plugins:
  - jekyll-sitemap

sass:
    sass_dir: ./_scss

include: ["_pages"]

permalink: /:title/
